development:
  adapter: postgresql
  database: hypem_dev
  username: kangmo
  password: test
  encoding: utf8
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: hypem_prod
  username: kangmo
  password: poop
  encoding: utf8
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: hypem_test
  username: kangmo
  password: test
  encoding: utf8
  host: localhost
  pool: 5